### ISSUE TITLE
Issue with HDL autocomplete

### ISSUE THREAD

**Issue by daniellperetz** [loyio/Nand2Tetris-vscode#2]
Sorry for writing here. I'm not working with github. 
This can be seen in the image below, the And16 autocomplete, autocompletes "a=" two times instead of "a=, b=".
Took me too long to notice.

![image](https://user-images.githubusercontent.com/81041155/151878766-cd90850a-f249-4ec9-8e90-04a4219ab583.png)

**Comment by loyio** [comment]
ok, get it, I will fix it
